POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email":"carlos@mail.com",
    "password": "carlos54321"
}

### Perfil

GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 3|efJB5LQcRQSsth5LVBRty5TeVH1P4TEgCLIdbNXz

###logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 3|efJB5LQcRQSsth5LVBRty5TeVH1P4TEgCLIdbNXz

